name: Update content submodule

on:
  schedule:
    - cron: '42 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:      # Allows manual triggering of the workflow

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the blog repository
      uses: actions/checkout@v3
      with:
        submodules: true  # Fetch all submodules

    - name: Set up Git user
      run: |
        git config --local user.name 'github-actions[bot]'
        git config --local user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Update dict submodule
      id: update_submodule
      run: |
        cd content
        git fetch
        LOCAL=$(git rev-parse @)
        REMOTE=$(git rev-parse FETCH_HEAD)
        if [ "$LOCAL" != "$REMOTE" ]; then
          echo "Submodule has updates"
          cd ..
          git submodule update --remote content
          git add content
          git commit -m "Update content to latest commit ${REMOTE}."
          echo "has_updates=true" >> $GITHUB_OUTPUT
        else
          echo "No updates in content."
          echo "has_updates=false" >> $GITHUB_OUTPUT
          exit 1  # Fail the step (and job) when there are no updates
        fi

    - name: Push changes
      if: steps.update_submodule.outputs.has_updates == 'true'
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
